### ISSUE TITLE
What was your accuracy for AlexNet Cifar - 100 model?

### ISSUE THREAD

**Issue by mukundkalantri23** [notem/keras-alexnet#1]
Also please help me understand why did you use class_count as 1000 when the total number of classes are 100? How much time did it take to train your model?

**Comment by notem** [comment]
The class count that is used is actually 100, not 1000, since the default class_count value is overwritten when I actually call the function. I am not sure why 1000 is set as the default, I assume it's a typo.

I vaguely remember that the performance of the model was comparable to the original paper's results (which is fairly low relative to what we expect from present-day state-of-the-art models).
